version: "3.9"

services:
  autotranslate:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEBUG=True
      - SELENIUM_URL=http://host.docker.internal:4444/wd/hub
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
      - "5678:5678"
    volumes:
      - .:/app


  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    shm_size: "2gb"
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    ports:
      - "4444:4444"


